// Generated by tools/service-worker.mjs - do not edit; see that file for the policy.
const BUILD = "6dae9cdeb72e"
const CACHE = "cl-" + BUILD
const PRECACHE = ["app-6735f071.js","prescript-2bfc6315.js","scripts-b3308c33.js","styles-79395ab0.css","static/fonts/ibmplexmono-v20--F63fjptAgt5VM-kVkqdyU8n1i8q1w.woff2","static/fonts/ibmplexmono-v20--F6qfjptAgt5VM-kVkqdyU8n3vAOwlBFgg.woff2"]
const scope = new URL(self.registration.scope)
// A file whose name is its content (a bundle's hash, a font's version path) can be taken from
// the browser's HTTP cache as it is. Anything else is revalidated when the worker fetches it:
// GitHub Pages' max-age=600 would otherwise hand a new build's worker the previous build's
// copy, and the new cache would be filled with the old site - which the first version of
// this worker did (caught by a deploy test: three views after a deploy, all old).
const immutable = (u) => /-[0-9a-f]{8}.(css|js)$/.test(u.pathname) || u.pathname.includes("/static/fonts/")
const get = (req, u) => fetch(req, immutable(u) ? {} : { cache: "no-cache" })

self.addEventListener("install", (event) => {
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE)
    // Each file on its own: one failure must not stop the worker installing.
    // The shell, plus the page(s) open right now: the page that registered this worker was
    // loaded before it existed, and is usually the home page - the one a returning reader
    // opens first. All of these are in the HTTP cache already, so this costs no network.
    const open = (await self.clients.matchAll({ type: "window", includeUncontrolled: true })).map((c) => {
      const u = new URL(c.url)
      u.hash = ""
      u.search = ""
      return u.href
    })
    await Promise.all([...PRECACHE.map((p) => new URL(p, scope).href), ...open].map(async (u) => {
      try {
        const res = await get(u, new URL(u))
        if (res.status === 200 && res.type === "basic") await cache.put(u, res)
      } catch {}
    }))
    await self.skipWaiting()
  })())
})

self.addEventListener("activate", (event) => {
  event.waitUntil((async () => {
    for (const k of await caches.keys()) if (k.startsWith("cl-") && k !== CACHE) await caches.delete(k)
    await self.clients.claim()
  })())
})

self.addEventListener("fetch", (event) => {
  const req = event.request
  if (req.method !== "GET") return
  const url = new URL(req.url)
  if (url.origin !== scope.origin || !url.pathname.startsWith(scope.pathname)) return
  if (url.pathname === scope.pathname + "sw.js") return
  // The cache key ignores the fragment and query; the site uses neither for content.
  url.hash = ""
  url.search = ""
  event.respondWith((async () => {
    const cache = await caches.open(CACHE)
    const hit = await cache.match(url)
    if (hit) return hit
    const res = await get(req, url)
    if (res.status === 200 && res.type === "basic") cache.put(url, res.clone()).catch(() => {})
    return res
  })())
})
